name: Release

on:
  workflow_dispatch:

jobs:
  pickup:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.pickup.outputs.versions }}
    steps:
    - uses: actions/checkout@v2

    - name: pickup
      id: pickup
      run: |
        find ${GITHUB_WORKSPACE} -type f -name Dockerfile | \
          sed -e "s|^${GITHUB_WORKSPACE}/||g" -e "s|/Dockerfile$||g" | \
          awk -v ORS="" 'BEGIN { print "versions=[" } { print "\"" $0 "\"," } END { print "]"}' | \
          sed -e "s|\,\]$|\]|" >> $GITHUB_OUTPUT

  build_and_push:
    runs-on: ubuntu-latest
    needs:
      - pickup
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        version: ${{ fromJSON( needs.pickup.outputs.versions ) }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.version }}"
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/pepabo/mysql:${{ matrix.version }}
