name: Release

on:
  workflow_dispatch:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set MYSQL_VERSION
        id: mysql
        run: |
          echo "version=$(cat ${GITHUB_WORKSPACE}/5.7/MYSQL_VERSION)" >> ${GITHUB_OUTPUT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:5.7"
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MYSQL_VERSION=${{ steps.mysql.outputs.version }}
          tags: |
            ghcr.io/pepabo/mysql:5.7
            ghcr.io/pepabo/mysql:${{ steps.mysql.outputs.version }}
